name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    
    using: 'node20'
    main: 'main.js'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5